### ISSUE TITLE
/getOriginalData endpoint giving duplicated data

### ISSUE THREAD

**Issue by MatthewFrieri** [Breaking-Bias/CashApp_FTL#52]
The endpoint gives data like this:
![image](https://github.com/user-attachments/assets/73e6d610-18a3-4919-96be-9156fd36b4ff)

Where if the transaction frequency for a given day was 50, then there are 50 entries for that day being returned. This repeats for every day so we're getting way too much duplicate data. 

I traced the problem to somewhere inside read_data.py create_formatted_data() where maybe the indexing of cleaned_data is wrong?

**Comment by Adventurer-E** [comment]
I'll resolve this problem in my next commit and push.
